/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-26 06:55:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member.Theme;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ThemeMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1689727807040L));
    _jspx_dependants.put("jar:file:/C:/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>TravelMaker</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"image/small_logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Theme/ThemeMain.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://unpkg.com/embla-carousel/embla-carousel.umd.js\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/embla-carousel-autoplay/embla-carousel-autoplay.umd.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <section id=\"middle\">\r\n");
      out.write("           \r\n");
      out.write("            <section class=\"container\">\r\n");
      out.write("                <section class=\"container0\"></section>\r\n");
      out.write("            \r\n");
      out.write("                <section class=\"container1\">\r\n");
      out.write("                    <div class=\"embla\" id=\"slideShow\">\r\n");
      out.write("                        \r\n");
      out.write("                            <div class=\"embla__container\">\r\n");
      out.write("                                <div class=\"embla__slide\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/ThemeMain1.png\" alt=\"Main1\">                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"embla__slide\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/ThemeMain2.png\" alt=\"Main2\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"embla__slide\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/ThemeMain3.png\" alt=\"Main3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"embla__slide\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/ThemeMain4.png\" alt=\"Main4\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <button class=\"embla__prev\">Prev</button>\r\n");
      out.write("                        <button class=\"embla__next\">Next</button>\r\n");
      out.write("                    </div>        \r\n");
      out.write("                </section>\r\n");
      out.write("            \r\n");
      out.write("                <section class=\"container2\"></section>\r\n");
      out.write("                <section class=\"container3\"><hr></section>\r\n");
      out.write("                <br>\r\n");
      out.write("                <section class=\"container4\">\r\n");
      out.write("                    <b>여진구의 테마 추천!</b>\r\n");
      out.write("                </section>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <section class=\"container5\">\r\n");
      out.write("                    <section class=\"flex-container1\">\r\n");
      out.write("                        <div class=\"item\" id=\"photo\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/autumnLOVE.jpg\">\r\n");
      out.write("                                <strong><h2>가을 타는 당신!</h2></strong>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 이름</b>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 주소</b>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\" id=\"photo\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/coupleTrip.jpg\">\r\n");
      out.write("                                <strong><h2>연인과 함께!</h2></strong>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 이름</b>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 주소</b>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\" id=\"photo\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/oldPalace.jpg\">\r\n");
      out.write("                                <strong><h2>역사.. 좋아하세요?</h2></strong>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 이름</b>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 주소</b>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\" id=\"photo\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/main/Disneyland.jpg\">\r\n");
      out.write("                                <strong><h2>5월은 가정의날!</h2></strong>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 이름</b>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <b>여행지 주소</b>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <section class=\"container6\">\r\n");
      out.write("                    <section class=\"container6-1\">\r\n");
      out.write("                        <b>키워드 & 해쉬태그</b>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    <section class=\"flex-container4\">\r\n");
      out.write("                        <div class=\"item3\" id=\"spring\">\r\n");
      out.write("                            #봄\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"childday\">\r\n");
      out.write("                            #어린이날\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"festival\">\r\n");
      out.write("                            #축제\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"flower\">\r\n");
      out.write("                            #벚꽃\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"bestfood\">\r\n");
      out.write("                            #맛집\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"activity\">\r\n");
      out.write("                            #액티비티\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"ocean\">\r\n");
      out.write("                            #바다\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"flex-container5\">\r\n");
      out.write("                        <div class=\"item3\" id=\"mountain\">\r\n");
      out.write("                            #산\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"couple\">\r\n");
      out.write("                            #커플\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"single\">\r\n");
      out.write("                            #싱글\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"bunggle\">\r\n");
      out.write("                            #벙글\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"family\">\r\n");
      out.write("                            #가족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"rain\">\r\n");
      out.write("                            #비\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item3\" id=\"train\">\r\n");
      out.write("                            #기차\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </section>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var emblaNode = document.querySelector('.embla')\r\n");
      out.write("        var options = { loop: false }\r\n");
      out.write("        var plugins = [EmblaCarouselAutoplay()] // Plugins\r\n");
      out.write("      \r\n");
      out.write("        var embla = EmblaCarousel(emblaNode, options, plugins)\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
