/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-31 01:50:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member.Theme;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ThemeCafe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1689727807040L));
    _jspx_dependants.put("jar:file:/C:/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>TravelMakerThemeCafe</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"image/small_logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Theme/ThemeCafe.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/ef988defcf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <section id=\"middle\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <section class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container1\">\r\n");
      out.write("                    <h2>Forest Outings</h2>\r\n");
      out.write("                    <b>눈과 입이 즐거워지는 곳</b>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container2\">\r\n");
      out.write("                    좋아요 0     조회수 0                    \r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container2-1\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container3\">\r\n");
      out.write("                    \r\n");
      out.write("                    <section class=\"flex_container1\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafe1.jpg\">\r\n");
      out.write("                          \r\n");
      out.write("                                \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafefood2.jpg\">\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/CafeMenu2.jpg\">\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafe3.jpg\">\r\n");
      out.write("                       \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>  \r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container4\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container5\">\r\n");
      out.write("                   \r\n");
      out.write("                            <b>이런 분들에게 추천해 드립니다!</b>\r\n");
      out.write("                            <p>감성적인 느낌을 좋아하는 분</p>\r\n");
      out.write("                            <p>빵과 커피에 진심인 분</p>\r\n");
      out.write("                            <p>눈과 입이 같이 즐거운게 행복한 분</p>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container6\">\r\n");
      out.write("                    <b>Forest Outings</b>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container7\">\r\n");
      out.write("                    <section class=\"container7-1\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/CafeMain.jpg\" alt=\"\">\r\n");
      out.write("                    </section>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container8\">\r\n");
      out.write("                    <section class=\"container8-1\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>사랑하는 연인과 함께 행복한 시간을 보낼수 있습니다.</li>\r\n");
      out.write("                                <li> 당신의 입과 눈을 행복하게 할 시간.</li>\r\n");
      out.write("                                <li>감성과 맛이 함께하는\r\n");
      out.write("                                    포레스트 아웃팅스에 오신 것을 환영합니다.</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("                    \r\n");
      out.write("                </section>\r\n");
      out.write("               \r\n");
      out.write("                <section class=\"container9\">\r\n");
      out.write("                    <section class=\"container9-1\">\r\n");
      out.write("                        <section class=\"item3\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/CafeRosetta.jpg\">\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\"item3\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafefood.jpg\">\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container10\">\r\n");
      out.write("                    <section class=\"container10-1\">\r\n");
      out.write("                        <section class=\"item4\">\r\n");
      out.write("                            <table>\r\n");
      out.write("                                 <ul>\r\n");
      out.write("                                    <li>포레스트 아웃팅스를 소개합니다!</li>\r\n");
      out.write("                                    <li>식물원인가 카페인가!?</li>\r\n");
      out.write("                                    <li>그냥 감성만 좋은게 아니라고!?</li>\r\n");
      out.write("                                    <li>빵이 그렇게 맛이 좋다며!?</li>\r\n");
      out.write("                                    <li>사진만 찍으면 나도 인플루언서!?</li>\r\n");
      out.write("                                    \r\n");
      out.write("                                 </ul>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"item4\">\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>MBTI 'E'와 'I'가 둘다 만족한다던데??</li>\r\n");
      out.write("                                    <li>매장에 와보면 한눈에 눈부터 즐거울 걸!?</li>\r\n");
      out.write("                                    <li> 'I'들을 위한 조용한 공간도 있던데!?</li>\r\n");
      out.write("                                    <li>시원한 숲속에 우리만의 공간이 있어!?</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                           </table>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container9\">\r\n");
      out.write("                    <section class=\"container9-1\">\r\n");
      out.write("                        <section class=\"item3\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafemenu4.jpg\">\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\"item3\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/Cafe/Cafemenu5.jpg\">\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container10\">\r\n");
      out.write("                    <section class=\"container10-1\">\r\n");
      out.write("                        <section class=\"item4\">\r\n");
      out.write("                            <table>\r\n");
      out.write("                                 <ul>\r\n");
      out.write("                                    <li>주차장도 넓어서 주차공간 걱정이 없다던데!?</li>\r\n");
      out.write("                                    <li>밥 배랑 디저트 배는 따로 있는거 알지!?</li>\r\n");
      out.write("                                    <li>커피 못 마셔도 걱정X! 에이드가 진짜 맛있거든!</li>\r\n");
      out.write("                                    <li>음료, 빵, 파스타, 피자, 스테이크도 있다던데!?</li>\r\n");
      out.write("                                    \r\n");
      out.write("                                 </ul>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"item4\">\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>위치 : 고양시 일산동구 고양대로 1124</li>\r\n");
      out.write("                                    <li>운영시간 : 10:00~22:00</li>\r\n");
      out.write("                                    <li>홈페이지 : http://www.forestoutings.co.kr/</li>\r\n");
      out.write("                                    <li>문의 : 031-963-0500</li>\r\n");
      out.write("                                    <li>주차 : 주차장완비</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                           </table>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            </section>    \r\n");
      out.write("           \r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
