/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-31 12:22:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member.Find;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findId_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1690298189670L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/travelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/travelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>아이디찾기</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Share/small_logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Find/findId.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/ef988defcf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("       \r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <section id=\"middle\">\r\n");
      out.write("           <div id=\"middlearea1\"></div>\r\n");
      out.write("           <div id=\"middlearea2\">\r\n");
      out.write("                <!-- 중간 영역 나눔 -->\r\n");
      out.write("                <div id=\"middle1-1\">\r\n");
      out.write("                    <div id=\"idtext\">아이디 찾기</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div id=\"middle1-2\">\r\n");
      out.write("                            <div class=\"findIdArea1\">\r\n");
      out.write("                                <div id=\"findIdArea1Text\">회원가입 시 등록한 질문에 대한 답변이 같아야, 아이디 찾기가 가능합니다.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"findIdArea2\">\r\n");
      out.write("                                <div class=\"textArea\">\r\n");
      out.write("                                    <div style=\"height: 60px;\"></div>\r\n");
      out.write("                                    <div style=\"height: 30px;\">\r\n");
      out.write("                                        <label for=\"nameInput\">\r\n");
      out.write("                                            <div style=\"width: 50px;\" class=\"idText2\">이름</div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"height: 30px;\"></div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label for=\"ism-Select\">\r\n");
      out.write("                                            <div style=\"width: 140px;\" class=\"idText2\">아이디 찾기 질문</div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"height: 13px;\"></div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <label for=\"answer-Input\">\r\n");
      out.write("                                            <div style=\"width: 140px;\" class=\"idText2\">아이디 찾기 답변</div>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"inputArea\"> \r\n");
      out.write("                                    <div style=\"height: 60px;\"></div>\r\n");
      out.write("                                    <div class=\"inputAreaName\">\r\n");
      out.write("                                        <input type=\"text\" id=\"nameInput\" name=\"memberName\" class=\"inputName\" autocomplete='off'>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"height: 23px;\"></div>\r\n");
      out.write("                                    <div style=\"height: 40px;\">\r\n");
      out.write("                                        <select id=\"ism-Select\" name=\"idQuestion\" class=\"questionSelect\">\r\n");
      out.write("                                            <option value=\"0\" selected>질문을 고르세요</option>\r\n");
      out.write("                                            <option value=\"1\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("                                            <option value=\"2\">자신의 인생 좌우명은?</option>\r\n");
      out.write("                                            <option value=\"3\">가장 기억에 남는 선생님 성함은?</option>\r\n");
      out.write("                                            <option value=\"4\">타인이 모르는 자신만의 신체비밀이 있다면?</option>\r\n");
      out.write("                                            <option value=\"5\">유년시절 가장 생각나는 친구 이름은?</option>\r\n");
      out.write("                                            <option value=\"6\">다시 태어나면 되고 싶은 것은?</option>\r\n");
      out.write("                                            <option value=\"7\">인상 깊게 읽은 책 이름은?</option>\r\n");
      out.write("                                            <option value=\"8\">자신의 별명이 있다면?</option>\r\n");
      out.write("                                            <option value=\"9\">받았던 선물 중 기억에 남는 독특한 선물은?</option>\r\n");
      out.write("                                            <option value=\"10\">자신의 보물 제 1호는?</option>\r\n");
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"height: 40px;\">\r\n");
      out.write("                                        <input type=\"text\" id=\"answer-Input\" name=\"answer\" class=\"answerInput\" autocomplete='off'>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                                \r\n");
      out.write("                            <div class=\"findIdArea3\">\r\n");
      out.write("                                <div class=\"findIdButtonArea1\"></div>\r\n");
      out.write("                                <div class=\"findIdButtonArea2\">\r\n");
      out.write("                                    <div class=\"a\">\r\n");
      out.write("                                        <button type=\"button\" id=\"findIdButton\" name=\"findId\">아이디 찾기</button>\r\n");
      out.write("                                        <button type=\"button\" id=\"cancelButton\" name =\"cancel\">취소</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>    \r\n");
      out.write("                <div id=\"middle1-3\">\r\n");
      out.write("                   \r\n");
      out.write("                        <div style=\"height: 45px;\"></div>\r\n");
      out.write("                        <div class=\"findIdArea4\">\r\n");
      out.write("                            <div class=\"findIdText\">\r\n");
      out.write("                                <div>회원 아이디</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 찾은 회원 아이디 나오게 하는 공간 -->\r\n");
      out.write("                            <div id=\"findIdTextArea\">\r\n");
      out.write("                                <span id=\"spanId\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"loginArea\">\r\n");
      out.write("                            <div class=\"loginArea1\"></div>\r\n");
      out.write("                            <div class=\"loginArea2\">\r\n");
      out.write("                                <button id=\"logindButton\"  onclick = \"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login'\">로그인 하기</button>\r\n");
      out.write("                                <button id=\"findPwButton\"  onclick = \"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/findPw'\">비밀번호 찾기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("           </div>\r\n");
      out.write("           <div id=\"middlearea3\"></div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("   \r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/Find/findId.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
