/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-12 09:47:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688964243119L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mainHomePage-style.css\">\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://unpkg.com/embla-carousel/embla-carousel.umd.js\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/embla-carousel-autoplay/embla-carousel-autoplay.umd.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<section id=\"middle\">\r\n");
      out.write("           \r\n");
      out.write("            <section class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("                <section class=\"container0\"></section>\r\n");
      out.write("                \r\n");
      out.write("                <section class=\"container1\">\r\n");
      out.write("                    <section style=\"display: flex;\">\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=b30c2e42-dd00-463a-b726-0e40b1d13bbb\" style=\"display:contents\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/sunset.png\"  style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=7cf983d9-35e7-49e0-914d-1e67665be577\" style=\"display:contents\">  -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/incheon.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=dad57d1b-05e5-4633-a85b-58e32d93b1fe\" style=\"display:contents\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/yeosu.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=3301d3ce-aa66-483d-8e78-66b4cac3a426\" style=\"display:contents\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/han-an.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=b3e8cc50-c792-4c9a-8fac-49376c99ef41\" style=\"display:contents\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/suwon.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=9b251ab6-7f28-4547-a5bb-508644372dc9\" style=\"display: contents\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/summerflower.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                        <!-- <a href=\"https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=e46d4b2f-5da4-40ad-ac69-f6492bfb6816\" style=\"display: contents;\"> -->\r\n");
      out.write("                            <img src=\"resources/images/homemain/chungnam.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                        <!-- </a> -->\r\n");
      out.write("                    </section>    \r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container2\">\r\n");
      out.write("                    <section style=\"width: 30px; position: relative; bottom:300px; font-size: 50px; color: white;\" ><</section>\r\n");
      out.write("                    <section style=\"width: 30px; float: right; position: relative; bottom: 360px; font-size: 50px; color: white;\">></section>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"container3\"><hr></section>\r\n");
      out.write("                <br>\r\n");
      out.write("                <section class=\"container4\">\r\n");
      out.write("                    <b>이달의 베스트 여행지 Top 10</b>\r\n");
      out.write("                </section>\r\n");
      out.write("                \r\n");
      out.write("                <section class=\"container5\">\r\n");
      out.write("                    <section class=\"flex-container1\">\r\n");
      out.write("                        <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                            <section class=\"item\" id=\"photo\">\r\n");
      out.write("                                <img src=\"resources/images/homemain/han-river.jpg\">\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <strong>\r\n");
      out.write("                               반포대교 달빛무지개 분수\r\n");
      out.write("                            </strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                            <section class=\"item\" id=\"photo\">\r\n");
      out.write("                                <img src=\"resources/images/homemain/bomunjeong.jpg\" >\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <strong>\r\n");
      out.write("                                보문정 (경주)\r\n");
      out.write("                            </strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                            <section class=\"item\" id=\"photo\">\r\n");
      out.write("                                <img src=\"resources/images/homemain/young-do.jpg\" >\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <strong>\r\n");
      out.write("                                영도 청학배수지 전망대\r\n");
      out.write("                            </strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                            <section class=\"item\" id=\"photo\">\r\n");
      out.write("                                <img src=\"resources/images/homemain/nam-i.JPG\" >\r\n");
      out.write("                            </section>\r\n");
      out.write("                            <strong>\r\n");
      out.write("                                남이섬\r\n");
      out.write("                            </strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <section style=\"height: 15px;\"></section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"nextSign\">\r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("                \r\n");
      out.write("                <section style=\"height: 30px;\"></section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container6\">\r\n");
      out.write("                    <b>테마</b>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"flex-container3\">\r\n");
      out.write("                    <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                        <section class=\"item2\" id=\"photo1\">\r\n");
      out.write("                            <img src=\"resources/images/homemain/chilgok.png\">\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            유유자적 걸으며 즐기는\r\n");
      out.write("                            <br>\r\n");
      out.write("                            경북 칠곡 여행\r\n");
      out.write("                        </strong>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                        <section class=\"item2\" id=\"photo1\">\r\n");
      out.write("                            <img src=\"resources/images/homemain/yangyang.png\" >\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            바닷바람을 만끽할 수 있는\r\n");
      out.write("                            <br>\r\n");
      out.write("                            강원 양양 여행\r\n");
      out.write("                        </strong>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\" style=\"text-decoration:none\">\r\n");
      out.write("                        <section class=\"item2\" id=\"photo1\">\r\n");
      out.write("                            <img src=\"resources/images/homemain/youngdong.png\" >\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <strong>\r\n");
      out.write("                            그림 같은 풍경이 펼쳐지는\r\n");
      out.write("                            <br>\r\n");
      out.write("                            충북 영동 여행\r\n");
      out.write("                        </strong>\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("           \r\n");
      out.write("        </section>\r\n");
      out.write("		\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var emblaNode = document.querySelector(\".container1\");\r\n");
      out.write("        var options = { loop: false };\r\n");
      out.write("        var plugins = [EmblaCarouselAutoplay()]; // Plugins\r\n");
      out.write("  \r\n");
      out.write("        var embla = EmblaCarousel(emblaNode, options, plugins);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
