/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-04 11:49:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688611724784L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/TravelMaker/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>TravelMaker</title>\r\n");
      out.write("    <script src=\"https://unpkg.com/embla-carousel/embla-carousel.umd.js\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/embla-carousel-autoplay/embla-carousel-autoplay.umd.js\"></script>\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Share/small_logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mainHomePage-style.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/ef988defcf.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/263168e067.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <section id=\"middle\">\r\n");
      out.write("           \r\n");
      out.write("            <section class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container0\"></section>\r\n");
      out.write("                    <div class=\"temp2\">\r\n");
      out.write("                        <button class=\"embla__prev2\"><</button>  \r\n");
      out.write("                        <div class=\"embla\">\r\n");
      out.write("                            <div class=\"viewport2\">\r\n");
      out.write("                                <div class=\"embla__container\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/sunset\" style=\"display:contents\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/sunset.png\"  style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/nightVeiw\" style=\"display:contents\"> \r\n");
      out.write("                                            <img src=\"resources/images/mainHome/incheon.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/yeosuSea\" style=\"display:contents\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/yeosu.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/hamyang\" style=\"display:contents\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/han-an.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/suwon\" style=\"display:contents\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/suwon.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/flower\" style=\"display: contents\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/summerflower.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"embla__slide\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/chungnam\" style=\"display: contents;\">\r\n");
      out.write("                                            <img src=\"resources/images/mainHome/chungnam.png\" style=\"width:100%;height:100%;object-fit:contain;\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div> \r\n");
      out.write("                            </div>       \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"embla__next2\">></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <section class=\"container2\">\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"container3\"></section>\r\n");
      out.write("                    <br>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"container4\">\r\n");
      out.write("                        <b>이달의 베스트 여행지 Top 10</b>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"container5\">\r\n");
      out.write("                    <div class=\"temp\">\r\n");
      out.write("                        <button class=\"embla__prev fa-solid fa-arrow-left\"></button>\r\n");
      out.write("                        <div class=\"embla1\">\r\n");
      out.write("                            <div class=\"embla__viewport\">\r\n");
      out.write("                                <div class=\"embla__container1\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=8&board=25\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Gangwon/phoenix.jpg\">\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                   휘닉스 블루캐니언\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=11&board=44\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Gyeongsang/sacheon.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    서천아이\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=8&board=23\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Gangwon/sokcho.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    속초 얼라이브 하트\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=5&board=8\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Busan/busanNamGu.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    오륙도 스카이워크\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=9&board=50\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Chungcheong/jecheon.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                  제천 용추폭포 유리전망대\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=9&board=62\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Chungcheong/jijoonghaeMaeul.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    지중해마을\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=9&board=49\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/mainHome/top10/danyang.PNG\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    단양 수양개빛터널\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=8&board=22\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Gangwon/jumunjin.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    주문진 해변\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=11&board=43\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/Region/Gyeongsang/gyeongju.jpg\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    월정교\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"embla__slide1\">\r\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Region/regionDetail?ctgr=8&board=21\" style=\"text-decoration:none\">\r\n");
      out.write("                                            <div class=\"photo item\">\r\n");
      out.write("                                                <img src=\"resources/images/mainHome/top10/haniranderpam.PNG\" >\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    하늬라벤더팜\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"embla__next fa-solid fa-arrow-right\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <br>\r\n");
      out.write("                <section class=\"container6\">\r\n");
      out.write("                    <b>테마</b>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"temp1\">\r\n");
      out.write("                        <button class=\"embla__prev1 fa-solid fa-arrow-left\"></button>\r\n");
      out.write("                        <div class=\"embla2\">\r\n");
      out.write("                            <div class=\"embla__viewport1\">\r\n");
      out.write("                                    <div class=\"embla__container2\">\r\n");
      out.write("                                        <div class=\"embla__slide2\">\r\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/famousRestaurant\" style=\"text-decoration:none\">\r\n");
      out.write("                                                <section class=\"item2 photo1\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/FamousRestaurant/Sub.png\">\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    서퍼의 천국 양양에 서퍼들이 반한 맛집!\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    솜다리 버거\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"embla__slide2\">        \r\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/coupleTrip\" style=\"text-decoration:none\">\r\n");
      out.write("                                                <section class=\"item2 photo1\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/CoupleTrip/CoupleTripArt1.jpg\" >\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    날 풀리기만 기다렸다면!? 김해로 커플여행 가즈앙!\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    경남 김해 커플여행 코스\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"embla__slide2\">\r\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/familyTrip\" style=\"text-decoration:none\">\r\n");
      out.write("                                                <section class=\"item2 photo1\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/FamilyTrip/FamilyTripSub.jpg\" >\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    아이와 나들이 떠나는 인천 여행 :)\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    인천 가족나들이 코스\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"embla__slide2\">\r\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/activity\" style=\"text-decoration:none\">\r\n");
      out.write("                                                <section class=\"item2 photo1\">\r\n");
      out.write("                                                    <img src=\"resources/images/mainHome/theme/activities.png\" >\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    더위와 스트레스 날려버릴\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    속이 뻥 뚫리는 액티비티\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"embla__slide2\">\r\n");
      out.write("                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/theme/trainTrip\" style=\"text-decoration:none\">\r\n");
      out.write("                                                <section class=\"item2 photo1\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ThemeBoard/TrainTrip/TrainTripTrain1.jpg\" >\r\n");
      out.write("                                                </section>\r\n");
      out.write("                                                <strong>\r\n");
      out.write("                                                    칙칙폭폭!! 기차타고 떠나요~\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    부산의 밤 풍경을 즐기는 여행(힐링코스)\r\n");
      out.write("                                                </strong>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                            </div>        \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"embla__next1 fa-solid fa-arrow-right\"></button>       \r\n");
      out.write("                    </div>       \r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        /* 메인 부분 */\r\n");
      out.write("\r\n");
      out.write("        var emblaNode = document.querySelector(\".viewport2\");\r\n");
      out.write("        var options = { loop: true };\r\n");
      out.write("        var plugins = [EmblaCarouselAutoplay()]; // Plugins\r\n");
      out.write("  \r\n");
      out.write("        var embla = EmblaCarousel(emblaNode, options, plugins);\r\n");
      out.write("\r\n");
      out.write("        // Grab button nodes\r\n");
      out.write("        const prevButtonNode2 = document.querySelector('.embla__prev2')\r\n");
      out.write("        const nextButtonNode2 = document.querySelector('.embla__next2')\r\n");
      out.write("\r\n");
      out.write("        // Add click listeners\r\n");
      out.write("        prevButtonNode2.addEventListener('click', embla.scrollPrev, true)\r\n");
      out.write("        nextButtonNode2.addEventListener('click', embla.scrollNext, true)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* 이달의 베스트 여행지 top10 부분 */\r\n");
      out.write("        \r\n");
      out.write("        // Grab wrapper nodes\r\n");
      out.write("        const rootNode = document.querySelector('.embla1')\r\n");
      out.write("        const viewportNode = rootNode.querySelector('.embla__viewport')\r\n");
      out.write("\r\n");
      out.write("        // Grab button nodes\r\n");
      out.write("        const prevButtonNode = document.querySelector('.embla__prev')\r\n");
      out.write("        const nextButtonNode = document.querySelector('.embla__next')\r\n");
      out.write("\r\n");
      out.write("        // Initialize the carousel\r\n");
      out.write("        const embla1 = EmblaCarousel(viewportNode)\r\n");
      out.write("\r\n");
      out.write("        // Add click listeners\r\n");
      out.write("        prevButtonNode.addEventListener('click', embla1.scrollPrev, false)\r\n");
      out.write("        nextButtonNode.addEventListener('click', embla1.scrollNext, false)\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        /* 테마 부분 */\r\n");
      out.write("\r\n");
      out.write("        // Grab wrapper nodes\r\n");
      out.write("        const rootNode1 = document.querySelector('.embla2')\r\n");
      out.write("        const viewportNode1 = rootNode1.querySelector('.embla__viewport1')\r\n");
      out.write("\r\n");
      out.write("        // Grab button nodes\r\n");
      out.write("        const prevButtonNode1 = document.querySelector('.embla__prev1')\r\n");
      out.write("        const nextButtonNode1 = document.querySelector('.embla__next1')\r\n");
      out.write("\r\n");
      out.write("        // Initialize the carousel\r\n");
      out.write("        const embla2 = EmblaCarousel(viewportNode1)\r\n");
      out.write("\r\n");
      out.write("        // Add click listeners\r\n");
      out.write("        prevButtonNode1.addEventListener('click', embla2.scrollPrev, false)\r\n");
      out.write("        nextButtonNode1.addEventListener('click', embla2.scrollNext, false)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
